[iOS] 자세히보기 Detail Usecase 구현(파워트레인, 구동방식, 바디타입, 휠, 추가옵션 상세정보)
softeerbootcamp-2nd/H3-UmochaRacer pull request #245
Opened 2023-08-25 14:27 UTC by eigen98

## 🔖 관련 이슈
- #231 

## 📝 구현 사항
- ImageDetailPopupViewController 자세히보기 뷰 컨트롤러 수정
    - 추가정보를 보여주는 뷰의 타입을 스택뷰로 변경하였습니다(UILabel -> UIStackView)
    - 일부 레이아웃을 수정하였습니다

- 추가 옵션 API의 Response값이 배열인 것을 나중에 알아서 배열인 경우와 단일 요소인 경우에 적절하게 보여줄 수 있도록 
usecase와 viewmodel을 적절하게 수정하였습니다.

- Usecase
    - info 데이터의 string을 정규표현식을 통해 title과 description을 분리하는 코드를 구현하였습니다.
    - 옵션선택 단계에 따라 Repository Layer에 API를 요청하는 메서드를 구현하였습니다.

## 📌 하고싶은 말
- 오늘 리허설하시느라 고생하셨습니다! 
준비를 너무 잘해주셔서 무사히 마칠 수 있었습니다ㅎㅎ

2023-08-26 17:30 UTC, sangyeon3 requested changes

2023-08-26 17:30 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +struct MockDetailOptionData: Decodable {
왜 이름이 다 mock인가요 ??

2023-08-26 17:30 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
이전 리뷰 댓글에서 파일 분리하겠다고 말씀주신 부분 같은데 분리해주시면 좋을 것 같아요

2023-08-26 17:30 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +                                      range: nil)
백카사전 태그 제거하는건가요?

2023-08-26 17:30 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +    private let networkService: NetworkServiceProtocol
파일 분리 부탁드립니다

이름도 mock으로 되어있는데 mock이 아닌거 같습니다. 혼동을 줄 수 있는 부분 수정해주시면 좋을 것 같아요~

2023-08-26 17:30 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +}
```swift
var parameters: HTTPParameter? {
    return nil
}
```

은 어떤가요 ㅎㅎ

2023-08-26 17:59 UTC, sangyeon3 reviewed
코드 정리가 너무 안 되어 있습니다 
안쓰는 코드, 주석이랑 print 지워주실 수 있나요ㅠ

2023-08-26 17:59 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/UseCase/DetailPopupUsecase.swift
> +            .eraseToAnyPublisher()
이렇게 되면 에러가 아예 뷰모델로 안 내려갈 것 같습니다. 

```swift
        return publisher
            .mapError { self.convertToDetailUsecaseError(from: $0) }
            .map { $0.toPresentation() }
            .eraseToAnyPublisher()
```

`func fetchAllAdditionalOptions(id: Int)`에서는 위와 같이 해주셨던데
이렇게 하지 않고 에러가 있으면 중간에 `Just(MockDetailOptionEntity(title: "", description: "", info: nil, imageSrc: nil))`로 리턴해주신 이유가 있으신가요?

2023-08-26 17:59 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +                self?.subTitleLabel.text = self?.step?.title ?? ""
subtitle 안쓰이는것 같은데 지워주시면 좋을 것 같아요

2023-08-26 18:28 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +struct MockDetailOptionData: Decodable {
아직 머지가 되지않은 자세히보기 관련 Repository가 따로 있고 이곳엔 레포지토리가 없어서 Mock으로 구현해두었습니다.
그런데 기존 Repository의 잘못된 부분이 많아서 여기서 구현한 Repository관련 코드로 모두 바꿀 것 같습니다. 
다만 네이밍이 겹치기때문에 일단 Mock으로 해두었습니다.

2023-08-26 18:31 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
새로운 PR에서 진행해도될까요? 기존 DetailRepository의 코드와 비교하면서 반영할부분과 제거할부분을 정하려고합니다.

2023-08-26 18:32 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +    private let networkService: NetworkServiceProtocol
여기에 있는 레포지토리 관련 코드는 모두 기존 DetailRepository의 코드와 비교하면서 반영할부분과 제거할부분을 정하려고합니다.

2023-08-26 18:41 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
그럼 Entity 파일 제외하고 리뷰하면 되는걸까요?? 아니면 전체적으로 다음 PR에서 하면 될까요?

2023-08-26 18:42 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
Mock붙은건 모두 제외해주시면 될 것 같습니다. 일괄적으로 수정할 생각이라 한 파일에 모아두었습니다.

2023-08-26 18:46 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
넵 늦은 시간까지 고생 많으십니다! DetailRepository 피알 머지했어요 ㅎㅎ

2023-08-26 18:46 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +
감사합니다! 상연님도 고생많으십니다 ㅎㅎ

2023-08-26 19:24 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +    }
뷰모델에서 output으로 selectedURStringRange를 보내주지 않아서 사용하지 않는부분 같습니다 .. !

2023-08-26 19:24 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +        descriptionTextView.text = result.fullText
해당 코드가 반복적으로 이루어지고 있는 것 같은데
URLabel의 setURString 내부에서 `ㅁ.text = ㅁ.fullText` 해줘도 좋겠네요 ~!

2023-08-26 19:24 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
>      }
함수화 하신거 좋네요 ~!

2023-08-26 19:24 UTC, sangyeon3 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupViewModel.swift
> -                    return Just(DetailInfo(title: "", subTitle: "", description: "", additionalInfo: "", imageURL: nil))
input으로 받은 page는 어디에 쓰이나요!?

2023-08-26 19:24 UTC, sangyeon3 commented on iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
> +}
UI 타겟에 있는 OptionCardCell에서 ImageDetailPopupViewController를 사용함으로써 ui 타겟 빌드가 안 된 거 같습니다 ..!

2023-08-26 19:25 UTC, sangyeon3 commented
수고하셨습니다 진짜 얼마 안남았네요! 화이팅입니다 ㅎㅎ

2023-08-27 03:20 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +}
스위치문 자체가 불필요하네요! 수정하였습니다.

2023-08-27 03:32 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/UseCase/DetailPopupUsecase.swift
> +            .eraseToAnyPublisher()
수정하였습니다!
이 usecase에서 자세히보기 요청 API의 종류가 2가지인데 같은 타입(`DetailOptionInfo`)의 데이터를 각각 배열 형태와 단일 요소 형태로 내려주는 것을 뒤늦게 알고 수정하다보니 일관성있게 구현하지 못하였네요.

2023-08-27 03:48 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +            }
수정하였습니다!
descriptionView에만 적용하던 함수를 다른 라벨에서도 적용할 수 있도록 수정했어야하는데 수정하지 않고 그대로 사용한 것 같습니다.

2023-08-27 03:51 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +    }
제거하였습니다!

2023-08-27 03:52 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
> +        descriptionTextView.text = result.fullText
좋습니다!
지금은 이렇게 두겠습니다. 버그 수정하시면서 수정해주셔도 좋습니다.

2023-08-27 07:02 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
> +                                      range: nil)
그 반대입니다. 백카사전 태그를 제외한 태그를 제거하기위한 조건식입니다.
추가정보에 key와 description 태그들이 따라오기 때문에 해당 태그들을 제거하기 위함입니다.

2023-08-27 08:46 UTC, eigen98 commented on iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupViewModel.swift
> -                    return Just(DetailInfo(title: "", subTitle: "", description: "", additionalInfo: "", imageURL: nil))
처음에 의도한건 자세히보기 정보를  한번의 API요청을 통해 배열의 형태로 저장해두고
page Index에 따라서 페이지컨트롤러를 통해 하나씩 자세히보기를 넘겨볼 수 있도록 구현하려고 하였습니다.
그 부분이 제대로 반영되어있지 않아서 다시 수정하였습니다.

2023-08-27 09:03 UTC, eigen98 commented on iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
> +}
아하 일단 UI타겟 추가해두겠습니다. 이런건 월요일에 일괄적으로 정리할까요?

2023-08-27 15:21 UTC, sangyeon3 commented on iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
> +}
넵 ㅎㅎ

2023-08-27 16:12 UTC, sangyeon3 reviewed
바쁘셨을텐데 고생하셨습니다! 머지할게요

2023-08-27 16:12 UTC, sangyeon3 approved these changes

2023-08-27 16:34 UTC, merged